FROM apache/airflow:2.0.0-python3.8
RUN pip install --no-cache-dir --user apache-airflow-providers-apache-cassandra
RUN pip install --no-cache-dir --user apache-airflow-providers-presto
RUN pip install --no-cache-dir --user scikit-learn